name: IOS CI
on:
  push:

jobs:
  run-ios-tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3.6.0
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Setup appium
      run: |
        npm install -g appium
        appium driver install xcuitest
        appium -v
        appium &>/dev/null &

    - name: Run Test
      run: ./gradlew test --info
    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: unit_test_report
        path: /Users/runner/work/


