name: IOS CI
on:
  push:

jobs:
  run-ios-tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3.6.0
      with:
        distribution: 'temurin'
        java-version: 11
    - name: List iOS Devices & Platforms
      run: |
        xcrun simctl list
    - name: Install iOS 11.4 Runtime
      run: |
        gem install xcode-install
        xcversion simulators --install='iOS 14.2'
    - name: Create and Run iOS Emulator - iPhoneX on iOS 14.2, Update default appium config for iOS
      run: |
        xcrun simctl create TestiPhoneX com.apple.CoreSimulator.SimDeviceType.iPhone-X com.apple.CoreSimulator.SimRuntime.iOS-14-2 > deviceid.txt 
        DEVICEUUID=`cat deviceid.txt`          
        echo $DEVICEUUID        
        xcrun simctl boot $DEVICEUUID 

    - name: Setup appium
      run: |
        npm install -g appium
        appium driver install xcuitest
        appium -v
        appium &>/dev/null &

    - name: Run Test
      run: ./gradlew test --info
    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: unit_test_report
        path: /Users/runner/work/


